
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Le Nhu Huynh - CE171797
 */
public class AboutUs extends javax.swing.JFrame {

    JLabel lb;

    /**
     * Creates new form HowToPlay
     */
    public AboutUs() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(980, 980);
        setLayout(new GridLayout(3, 1, 5, 5));
        lb = new JLabel("About Us");
        lb.setHorizontalAlignment(JLabel.CENTER);
        lb.setForeground(Color.red);
        add(lb);
        lb.setFont(new Font("Courier", Font.BOLD, 60));

        JPanel textPanel = new JPanel(new GridLayout(1, 1));
        JTextArea txt;

        txt = new JTextArea("FPT University - SE1707 - SU23 - CSD201 - Instructor: TuVH6\n"
                + "We are Horizon. \n"
                + "We would like to share with you our Sudoku game.\n"
                + "Hope you enjoy with our game.\n"
                + "Our members:\n"
                + "| Tran Gia Huy - CE170732 \n| Tran Cong Chinh - CE171816 \n| Tran Nguyen Nam Thuan - CE171497 \n| Le Nhu Huynh - CE171797 \n| Pham Tan Phat - CE172093");
        txt.setFont(new Font("Courier", Font.BOLD, 20));
        txt.setEditable(false);

        // Wrap the text area in a JScrollPane
        JScrollPane scrollPane = new JScrollPane(txt);
        textPanel.add(scrollPane);
        add(textPanel);

        JButton btHome = new JButton("Home");
        btHome.addActionListener((ActionEvent e) -> {
            Home h = new Home();
            h.setVisible(true);
            this.setVisible(false);
        });
        btHome.setFont(new Font("Courier", Font.BOLD, 60));

        add(btHome);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HowToPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HowToPlay().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
