
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tran Cong Chinh - CE171816
 */
public class HowToPlay extends javax.swing.JFrame {

    JLabel lb;

    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1300, 980);
        setLayout(new GridLayout(3, 1, 5, 5));
        lb = new JLabel("How to play Sudoku");
        lb.setHorizontalAlignment(JLabel.CENTER);
        lb.setForeground(Color.red);
        add(lb);
        lb.setFont(new Font("Courier", Font.BOLD, 60));
        JTextArea txt = new JTextArea("+ Horizontal row: Must have all the numbers from 1 to 9, do not have the same number and do not need to be in the correct order.\n"
                + "+ Vertical line: Make sure there are enough numbers from 1 to 9, no duplicate numbers, no need to be in order.\n"
                + "+ Each 3x3 area: There must be enough numbers from 1-9 and no duplicates in the same 3x3 area.");
        add(txt);
        txt.setFont(new Font("Courier", Font.BOLD, 20));
        txt.setEditable(false);
        JButton btHome = new JButton("Home");
        btHome.addActionListener((ActionEvent e) -> {
            Home h = new Home();
            h.setVisible(true);
            this.setVisible(false);
        });
        add(btHome);
        btHome.setFont(new Font("Courier", Font.BOLD, 60));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
